# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the `pg` gem:
#
#   gem "pg"
#
# And ensure that your development database is configured to use UTF8.
#
#   ensure that your development database is configured to use UTF8.
#
#   For more information on configuring your database, check out
#   http://guides.rubyonrails.org/configuring.html
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: spark
  password: password
#  host: db

development:
  <<: *default
  database: spark_clinic_development

  # The specified database role needs to be able to create databases for
  # schema creation via `rails db:create`
  # You can set this to false if you're using a pre-existing database
  # and don't want Rails to attempt to create it.
  # create_database: false

# Warning: The database defined as "test" will be erased and
# re-created to ensure it is in a pristine state every run.
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: spark_clinic_test
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  username: <%= ENV.fetch("PGUSER") { "spark" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "password" } %>

# As with config/credentials.yml, you should store your production database here with credentials it's best kept outside of source control.
# Use the `rails db:encrypt` command to encrypt a production database.yml file.
#
# production:
#   <<: *default
#   database: spark_clinic_production
#   username: spark_clinic
#   password: <%= ENV["SPARK_CLINIC_DATABASE_PASSWORD"] %>